// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.

import 'dart:core';
import 'package:dart_json_mapper/src/model/annotations.dart' as prefix0;
import 'package:flutter_app_template/net/model/res/domain_config.dart'
    as prefix1;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const

// ignore:unused_import
import 'package:reflectable/mirrors.dart' as m;
// ignore:unused_import
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
// ignore:unused_import
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.JsonSerializable(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'DomainConfig',
            r'.DomainConfig',
            134217735,
            0,
            const prefix0.JsonSerializable(),
            const <int>[0, 1, 2, 3, 4, 5, 6, 7, 16],
            const <int>[17, 18, 19, 20, 21, 8, 9, 10, 11, 12, 13, 14, 15],
            const <int>[],
            -1,
            {},
            {},
            {
              r'': (bool b) => (createdAt, createdBy, domainDesc, domainStatus,
                      id, updatedAt, updatedBy, domain) =>
                  b
                      ? prefix1.DomainConfig(createdAt, createdBy, domainDesc,
                          domainStatus, id, updatedAt, updatedBy, domain)
                      : null
            },
            -1,
            0,
            const <int>[],
            const <Object>[prefix0.jsonSerializable],
            null)
      ],
      <m.DeclarationMirror>[
        r.VariableMirrorImpl(
            r'domain',
            134349829,
            0,
            const prefix0.JsonSerializable(),
            -1,
            1,
            1, const <int>[], const []),
        r.VariableMirrorImpl(
            r'createdAt',
            134349829,
            0,
            const prefix0.JsonSerializable(),
            -1,
            1,
            1, const <int>[], const []),
        r.VariableMirrorImpl(
            r'createdBy',
            134349829,
            0,
            const prefix0.JsonSerializable(),
            -1,
            1,
            1, const <int>[], const []),
        r.VariableMirrorImpl(
            r'domainDesc',
            134349829,
            0,
            const prefix0.JsonSerializable(),
            -1,
            1,
            1, const <int>[], const []),
        r.VariableMirrorImpl(
            r'domainStatus',
            134349829,
            0,
            const prefix0.JsonSerializable(),
            -1,
            2,
            2, const <int>[], const []),
        r.VariableMirrorImpl(
            r'id',
            134349829,
            0,
            const prefix0.JsonSerializable(),
            -1,
            2,
            2, const <int>[], const []),
        r.VariableMirrorImpl(
            r'updatedAt',
            134349829,
            0,
            const prefix0.JsonSerializable(),
            -1,
            1,
            1, const <int>[], const []),
        r.VariableMirrorImpl(
            r'updatedBy',
            134349829,
            0,
            const prefix0.JsonSerializable(),
            -1,
            1,
            1, const <int>[], const []),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 0, 8),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 1, 9),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 2, 10),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 3, 11),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 4, 12),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 5, 13),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 6, 14),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 7, 15),
        r.MethodMirrorImpl(
            r'',
            0,
            0,
            -1,
            0,
            0,
            const <int>[],
            const <int>[0, 1, 2, 3, 4, 5, 6, 7],
            const prefix0.JsonSerializable(),
            const []),
        r.MethodMirrorImpl(r'==', 2097154, -1, -1, 3, 3, const <int>[],
            const <int>[8], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(r'toString', 2097154, -1, -1, 1, 1, const <int>[],
            const <int>[], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(
            r'noSuchMethod',
            524290,
            -1,
            -1,
            -1,
            -1,
            const <int>[],
            const <int>[9],
            const prefix0.JsonSerializable(),
            const []),
        r.MethodMirrorImpl(r'hashCode', 2097155, -1, -1, 2, 2, const <int>[],
            const <int>[], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(r'runtimeType', 2097155, -1, -1, 4, 4, const <int>[],
            const <int>[], const prefix0.JsonSerializable(), const [])
      ],
      <m.ParameterMirror>[
        r.ParameterMirrorImpl(
            r'createdAt',
            134349830,
            16,
            const prefix0.JsonSerializable(),
            -1,
            1,
            1,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'createdBy',
            134349830,
            16,
            const prefix0.JsonSerializable(),
            -1,
            1,
            1,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'domainDesc',
            134349830,
            16,
            const prefix0.JsonSerializable(),
            -1,
            1,
            1,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'domainStatus',
            134349830,
            16,
            const prefix0.JsonSerializable(),
            -1,
            2,
            2,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'id',
            134349830,
            16,
            const prefix0.JsonSerializable(),
            -1,
            2,
            2,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'updatedAt',
            134349830,
            16,
            const prefix0.JsonSerializable(),
            -1,
            1,
            1,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'updatedBy',
            134349830,
            16,
            const prefix0.JsonSerializable(),
            -1,
            1,
            1,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'domain',
            134349830,
            16,
            const prefix0.JsonSerializable(),
            -1,
            1,
            1,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'other',
            134348806,
            17,
            const prefix0.JsonSerializable(),
            -1,
            5,
            5,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'invocation',
            134348806,
            19,
            const prefix0.JsonSerializable(),
            -1,
            6,
            6,
            const <int>[],
            const [],
            null,
            null)
      ],
      <Type>[prefix1.DomainConfig, String, int, bool, Type, Object, Invocation],
      1,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'domain': (dynamic instance) => instance.domain,
        r'createdAt': (dynamic instance) => instance.createdAt,
        r'createdBy': (dynamic instance) => instance.createdBy,
        r'domainDesc': (dynamic instance) => instance.domainDesc,
        r'domainStatus': (dynamic instance) => instance.domainStatus,
        r'id': (dynamic instance) => instance.id,
        r'updatedAt': (dynamic instance) => instance.updatedAt,
        r'updatedBy': (dynamic instance) => instance.updatedBy
      },
      {},
      null,
      [])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
